trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - README.md
      - Logs/*

pool: 'Aida'

workspace:
    clean: all

name: $(Date:yy.MM.dd.HHmm)

steps:
- task: UseDotNet@2
  displayName: "Use NetCore 3.1"
  inputs:
    packageType: 'runtime'
    version: '3.1.x'

- task: DotNetCoreCLI@2
  displayName: "Restore"
  inputs:
    command: 'restore'
    projects: 'StringCalculator.sln'
    arguments: "--configuration Release"
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: "Build"
  inputs:
    command: 'build'
    projects: 'StringCalculator.sln'
    arguments: "--configuration Release --no-restore"

- task: DotNetCoreCLI@2
  displayName: "Test"
  inputs:
    command: 'test'
    projects: 'StringCalculator.sln'
    arguments: "--configuration Release --no-restore --no-build"

- task: DotNetCoreCLI@2
  displayName: "Publish"
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments : '--output $(Build.ArtifactStagingDirectory) --configuration Release --no-restore --no-build'

- task: PublishBuildArtifacts@1
  displayName: "Drop Artifact"
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
